<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>av_controller</name>
  <version>0.0.0</version>
  <description>AV controller ROS2 nodes</description>
  <maintainer email="3225961569@qq.com">wangh</maintainer>
  <license>MIT</license>

  <buildtool_depend>ament_cmake</buildtool_depend>
  <buildtool_depend>ament_cmake_python</buildtool_depend>

  <depend>rclcpp</depend>
  <depend>rclpy</depend>
  <depend>av_control_msgs</depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
